name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Isso avisa o GitHub que todos os comandos rodam dentro da subpasta
    defaults:
      run:
        working-directory: nome-do-peso

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test -- --coverage
      continue-on-error: true

    - name: Build Application
      run: npm run build

        - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: nome-do-peso/build
        branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
        clean: true
